version: 0.2
phases:
  pre_build:
    commands:
      - go version
      - go test
  build:
    commands:
      - GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap lambda.go service.go
      - zip -q -r deployment.zip bootstrap
  post_build:
    commands:
      - echo updating $FUNCTION_NAME
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file=fileb://deployment.zip
